boost: fix use of deprecated ice_not traits.
The boost folks removed ice_not in 1.60 but forgot to update
boost::graph accordingly. Now any use of adjacency_matrix.hpp
fails:

    $ cat test.cpp
    #include <boost/graph/adjacency_list.hpp>
    #include <boost/graph/adjacency_matrix.hpp>

    $ clang++ -c test.cpp -I/usr/local/include
    In file included from test.cpp:2:
    /usr/local/include/boost/graph/adjacency_matrix.hpp:446:38: error: no member
          named 'ice_not' in namespace 'boost::type_traits'
        BOOST_STATIC_ASSERT(type_traits::ice_not<(is_same<Directed, bidirect...
                            ~~~~~~~~~~~~~^

This is upstream Boost bug https://svn.boost.org/trac/boost/ticket/11880.

Fix this by applying the upstream patch, boostorg/graph@1d5f43d.

Closes Homebrew/homebrew#48262.

Signed-off-by: Tim D. Smith <git@tim-smith.us>