workflows: use PAT instead of default GITHUB_TOKEN
Should prevent errors like:

Error: [{"type"=>"FORBIDDEN", "path"=>["repository", "pullRequest", "reviews", "nodes", 0, "author", "email"], "extensions"=>{"saml_failure"=>false}, "locations"=>[{"line"=>6, "column"=>27}], "message"=>"Resource not accessible by integration"}]

https://github.com/Homebrew/homebrew-core/runs/826063506?check_suite_focus=true#step:7:20