root: various tweaks
- depend on pcre and xz
- depend on python instead of :python
- depend on gcc instead of :fortran
- use elisp directory helper
- cleanup python usage
- test python bindings
- limit remote fetching
- disable trying to find MySQL

Otherwise, if you have it installed, this happens:

```
In file included from /tmp/root-20180109-13813-1cfytpu/root-6.12.04/sql/mysql/src/TMySQLResult.cxx:12:
/tmp/root-20180109-13813-1cfytpu/root-6.12.04/builddir/include/TMySQLResult.h:17:10: fatal error: 'mysql.h' file not found
\#include <mysql.h>
         ^~~~~~~~~
1 error generated.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f sql/pgsql/CMakeFiles/PgSQL.dir/build.make sql/pgsql/CMakeFiles/PgSQL.dir/depend
make[2]: *** [sql/mysql/CMakeFiles/RMySQL.dir/src/TMySQLResult.cxx.o] Error 1
make[1]: *** [sql/mysql/CMakeFiles/RMySQL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Closes #22648.

Signed-off-by: ilovezfs <ilovezfs@icloud.com>