exim: fix StringInreplaceExtension failure during build
Building this formula was failing with:

  Error: An exception occurred within a child process:
    NoMethodError: undefined method `<<' for #<StringInreplaceExtension:0x00007f8e14afe278>

I guess this formula syntax must have been valid at some point since
it's been there for years, but it doesn't seem to work anymore.

Just append to the file as a separate step.

Closes #67349.

Signed-off-by: Sean Molenaar <1484494+SMillerDev@users.noreply.github.com>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>